import { mkdirSync, writeFileSync } from "fs";
import { join } from "path";
import { watch } from "fs";
import type { Command } from "commander";
import {
  loadAgent,
  loadBlocks,
  renderMarkdown,
  computeSourceHash,
} from "../core/index.js";
import { getGeneratedPath, getInstructionsPath, getManifestPath } from "../utils/paths.js";

const VERSION = "0.1.0";

export function registerCompileCommand(program: Command): void {
  program
    .command("compile <agent-path>")
    .description("Compile agent manifest and blocks to Markdown")
    .option(
      "--include-draft",
      "Include draft-status blocks (default: exclude)",
      false
    )
    .option(
      "--include-block-comments",
      "Include block metadata as comments",
      false
    )
    .option("--watch", "Watch for changes and recompile", false)
    .action((agentPath: string, options) => {
      compileAgent(agentPath, {
        includeDraft: options.includeDraft,
        includeBlockComments: options.includeBlockComments,
        watch: options.watch,
      });
    });
}

interface CompileOptions {
  includeDraft: boolean;
  includeBlockComments: boolean;
  watch?: boolean;
}

function performCompile(agentPath: string, options: CompileOptions): void {
  try {
    const manifest = loadAgent(agentPath);
    let blocks = loadBlocks(agentPath);

    // Filter blocks by status
    if (!options.includeDraft) {
      blocks = blocks.filter((b) => b.status !== "draft");
    }
    blocks = blocks.filter((b) => b.status !== "deprecated");

    // Compute hash before rendering
    const sourceHash = computeSourceHash(manifest, blocks);

    // Render Markdown
    const markdown = renderMarkdown(manifest, blocks, {
      includeBlockComments: options.includeBlockComments,
    });

    // Generate header with metadata
    const header = `<!--
Generated by agentctl. Do not edit this file manually.
Source: agents/${manifest.id}/
source-hash: sha256:${sourceHash}
agentctl-version: ${VERSION}
-->

`;

    const content = header + markdown;

    // Write to generated/{id}.md
    const generatedPath = getGeneratedPath(agentPath);
    mkdirSync(generatedPath, { recursive: true });

    const outputFile = join(generatedPath, `${manifest.id}.md`);
    writeFileSync(outputFile, content, "utf-8");

    console.log(
      `Compiled agent ${manifest.id} | Blocks: ${blocks.length} | Hash: ${sourceHash}`
    );
  } catch (error) {
    console.error(
      `Error: ${error instanceof Error ? error.message : String(error)}`
    );
    if (!options.watch) {
      process.exit(1);
    }
  }
}

function compileAgent(agentPath: string, options: CompileOptions): void {
  // Perform initial compile
  performCompile(agentPath, options);

  // If watch mode, set up file watcher
  if (options.watch) {
    console.log(`\nWatching for changes in ${agentPath}...`);

    const manifestPath = getManifestPath(agentPath);
    const instructionsPath = getInstructionsPath(agentPath);

    // Watch manifest
    watch(manifestPath, () => {
      console.log("\nManifest changed, recompiling...");
      performCompile(agentPath, options);
    });

    // Watch instructions directory
    watch(instructionsPath, () => {
      console.log("\nInstructions changed, recompiling...");
      performCompile(agentPath, options);
    });

    // Keep process alive
    console.log("Press Ctrl+C to stop watching.");
  }
}
